#!/usr/bin/env php
<?php

require __DIR__ . '/vendor/autoload.php';

try {
// Load environment
    putenv('BASE_DIR='.realpath(__DIR__));
    $dotenv = \Dotenv\Dotenv::create(getenv('BASE_DIR'));
    $dotenv->load();
} catch (Exception $e) {
    echo "\n\n\n\t /!\ Unable to load any .env file at the root of this project. Some commands may fail /!\ \n\n\n";
}


use Symfony\Component\Console\Application;

use Commands\Migration\CreateMigrationCommand;
use Commands\Migration\RunMigrationCommand;

use Commands\Seed\CreateSeedCommand;
use Commands\Seed\RunSeedCommand;

use Commands\Asset\CompileCommand;

use Commands\Secret\GenerateSecretCommand;

use Commands\Initialization\InitializationCommand;

use Commands\Controller\ControllerGeneratorCommand;

use Commands\Cache\CacheClearCommand;

$application = new Application();

/*
 * Initialization command
 */
$application->add(new InitializationCommand());

/*
 * Migration commands
 */
$application->add(new CreateMigrationCommand());
$application->add(new RunMigrationCommand());

/*
 * Seed commands
 */
$application->add(new CreateSeedCommand());
$application->add(new RunSeedCommand());

/*
 * Assets management commands
 */
$application->add(new CompileCommand());

/*
 * Secret generator
 */
$application->add(new GenerateSecretCommand());

/*
 * Cache commands
 */
$application->add(new CacheClearCommand());

/*
 * Controller commands
 */
$application->add(new ControllerGeneratorCommand());

$application->run();
