#!/usr/bin/env php
<?php

require __DIR__ . '/vendor/autoload.php';

// Load environment
putenv('BASE_DIR='.realpath(__DIR__));
$dotenv = \Dotenv\Dotenv::create(getenv('BASE_DIR'));
$dotenv->load();

use Symfony\Component\Console\Application;

use Commands\Migration\CreateMigrationCommand;
use Commands\Migration\RunMigrationCommand;

use Commands\Seed\CreateSeedCommand;
use Commands\Seed\RunSeedCommand;

use Commands\Asset\CompileCommand;

use Commands\Secret\GenerateSecretCommand;

use Commands\Initialization\InitializationCommand;

$application = new Application();

/*
 * Initialization command
 */
$application->add(new InitializationCommand());

/*
 * Migration commands
 */
$application->add(new CreateMigrationCommand());
$application->add(new RunMigrationCommand());

/*
 * Seed commands
 */
$application->add(new CreateSeedCommand());
$application->add(new RunSeedCommand());

/*
 * Assets management commands
 */
$application->add(new CompileCommand());

/*
 * Secret generator
 */
$application->add(new GenerateSecretCommand());

$application->run();
