#!/usr/bin/env php
<?php

require _DIR_.'/../vendor/autoload.php';

try {
    echo "\n\n ********************************************** \n\n";
    echo "Start SCSS compilation to .min.css files .... \n";

    $scss = new Leafo\ScssPhp\Compiler();
    $globDir = __DIR__ . '/scss/*.scss';
    $outputDir = __DIR__ . '/../public/css/';
    foreach (glob($globDir) as $sassFile) {

        $sassFileName = basename($sassFile);
        $explodedFileName = explode('.', $sassFileName);
        $sassFileNameNoExt = $explodedFileName[0];

        echo "------------------\n";
        echo "Compiling : $sassFileName ... \n";

        $sassContent = file_get_contents($sassFile);
        $compiledContent = $scss->compile($sassContent);
        $compiledCssFileName = $sassFileNameNoExt.'.min.css';
        $compiledFullFilePath = $outputDir.$compiledCssFileName;

        $minifier = new MatthiasMullie\Minify\CSS($compiledContent);

        if (!file_put_contents($compiledFullFilePath, $minifier->minify())) {
            echo "\t ==> /!\ Unable to compile $sassFileName /!\ \n";
        } else {
            echo "\t ==> Compiled to : ./public/css/$compiledCssFileName\n";
        }
        echo "------------------\n";
    }
    echo "SCSS compilation DONE !";

    echo "\n\n ********************************************** \n\n";
    echo "Start JS compilation to .min.js files .... \n";

    $globDir = __DIR__ . '/js/*.js';
    $outputDir = __DIR__ . '/../public/js/';

    foreach (glob($globDir) as $jsFile) {
        $jsFileName = basename($jsFile);
        $explodedFileName = explode('.', $jsFileName);
        $jsFileNameNoExt = $explodedFileName[0];

        echo "------------------\n";
        echo "Compiling : $jsFileName ... \n";

        $minifier = new MatthiasMullie\Minify\JS($jsFile);

        $compiledJsFileName = $jsFileNameNoExt.'.min.js';
        $compiledFullFilePath = $outputDir.$compiledJsFileName;

        if (!file_put_contents($compiledFullFilePath, $minifier->minify())) {
            echo "\t ==> /!\ Unable to compile $jsFileName /!\ \n";
        } else {
            echo "\t ==> Compiled to : ./public/js/$compiledJsFileName\n";
        }
        echo "------------------\n";
    }
    exit;
} catch (Exception $e) {
    echo "ERROR : ".$e->getMessage(). "\n";
    exit;
}

 ?>
